In [ ]:
import numpy as np
from random import sample
from numpy import *
import random
np.set_printoptions(threshold=np.inf)
import pandas as pd
from pandas import DataFrame as df

In [ ]:
ind=np.arange(1,501)
money=np.random.randint(1000,1500,size=(500))
sum=[]
for i in range(500):
  x=[ind[i],money[i]]
  sum=sum+x
sum=np.array(sum)
sum.resize(500,2)
sum

array([[   1, 1209],
       [   2, 1491],
       [   3, 1292],
       [   4, 1421],
       [   5, 1322],
       [   6, 1412],
       [   7, 1402],
       [   8, 1257],
       [   9, 1350],
       [  10, 1169],
       [  11, 1024],
       [  12, 1260],
       [  13, 1381],
       [  14, 1395],
       [  15, 1495],
       [  16, 1418],
       [  17, 1154],
       [  18, 1345],
       [  19, 1102],
       [  20, 1115],
       [  21, 1294],
       [  22, 1203],
       [  23, 1309],
       [  24, 1483],
       [  25, 1244],
       [  26, 1234],
       [  27, 1187],
       [  28, 1260],
       [  29, 1082],
       [  30, 1336],
       [  31, 1440],
       [  32, 1057],
       [  33, 1043],
       [  34, 1113],
       [  35, 1402],
       [  36, 1384],
       [  37, 1409],
       [  38, 1342],
       [  39, 1472],
       [  40, 1357],
       [  41, 1474],
       [  42, 1441],
       [  43, 1299],
       [  44, 1122],
       [  45, 1200],
       [  46, 1462],
       [  47, 1400],
       [  48,

In [ ]:
stocks=['A','B','C','D','E']
stocks
array_3= full(500,0)
array_3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
X=[]
for i in range(500):
  x=random.sample(stocks,3)
  X=X+x
X=np.array(X)
X.resize(500,3)
X

array([['D', 'B', 'E'],
       ['A', 'C', 'D'],
       ['A', 'C', 'E'],
       ['A', 'C', 'B'],
       ['C', 'E', 'A'],
       ['D', 'E', 'A'],
       ['C', 'B', 'D'],
       ['C', 'D', 'A'],
       ['E', 'B', 'A'],
       ['A', 'E', 'B'],
       ['B', 'E', 'A'],
       ['D', 'C', 'B'],
       ['A', 'D', 'B'],
       ['C', 'E', 'D'],
       ['D', 'B', 'C'],
       ['C', 'A', 'B'],
       ['C', 'D', 'E'],
       ['C', 'D', 'E'],
       ['C', 'B', 'E'],
       ['D', 'B', 'A'],
       ['B', 'A', 'C'],
       ['A', 'B', 'E'],
       ['E', 'C', 'A'],
       ['E', 'B', 'A'],
       ['D', 'C', 'B'],
       ['E', 'A', 'D'],
       ['A', 'C', 'E'],
       ['C', 'A', 'E'],
       ['E', 'A', 'B'],
       ['A', 'B', 'E'],
       ['E', 'B', 'D'],
       ['E', 'C', 'D'],
       ['E', 'B', 'C'],
       ['A', 'B', 'C'],
       ['E', 'D', 'B'],
       ['D', 'E', 'B'],
       ['D', 'C', 'B'],
       ['D', 'B', 'C'],
       ['C', 'B', 'A'],
       ['A', 'D', 'B'],
       ['B', 'C', 'D'],
       ['A', 'C'

In [ ]:
inv=np.arange(250,501)
duplicate= sum.copy()
A=[]
B=[]
C=[]
D=[]
E=[]

In [ ]:
data={'Customer_ID': ind,
      'Total_money': money,
      'A':array_3,
      'B':array_3,
      'C':array_3,
      'D':array_3,
      'E':array_3}

In [ ]:
df_1=pd.DataFrame(data)

In [ ]:
df_1

Customer_ID  Total_money  A  B  C  D  E
0              1         1209  0  0  0  0  0
1              2         1491  0  0  0  0  0
2              3         1292  0  0  0  0  0
3              4         1421  0  0  0  0  0
4              5         1322  0  0  0  0  0
..           ...          ... .. .. .. .. ..
495          496         1167  0  0  0  0  0
496          497         1396  0  0  0  0  0
497          498         1075  0  0  0  0  0
498          499         1063  0  0  0  0  0
499          500         1029  0  0  0  0  0

[500 rows x 7 columns]

In [ ]:
a1= np.char.count(X,'A')
sum_a1= a1.sum()

In [ ]:
b1= np.char.count(X,'B')
sum_b1= b1.sum()

In [ ]:
c1= np.char.count(X,'C')
sum_c1= c1.sum()

In [ ]:
d1= np.char.count(X,'D')
sum_d1=d1.sum()

In [ ]:
e1= np.char.count(X,'E')
sum_e1=e1.sum()

In [ ]:
sum1= [sum_a1,sum_b1,sum_c1,sum_d1,sum_e1]
sum1

[278, 306, 319, 292, 305]

In [ ]:
max1= max(sum1)

In [ ]:
if max1 == sum_a1:
  print('A')
  ans='A'
elif max1 == sum_b1:
  print('B')
  ans='B'
elif max1 == sum_c1:
  print('C')
  ans='C'
elif max1 == sum_d1:
  print('D')
  ans='D'
elif max1 == sum_e1:
  print('E')
  ans='E'

C


In [ ]:
arr= np.arange(250,500)
money_new= money.copy()

In [ ]:
new_array=[]
for i in range(500):
  for j in range(0,3):
    if j==1 or j==0:
      inv_share= np.random.choice(arr)
      new_array.append(inv_share)
      money[i]= money[i]-inv_share
    if j==2:
      inv_share= money[i]
      if inv_share>500:
        new_array.append(0)
      else:
        new_array.append(inv_share)

In [ ]:
new_array= np.array(new_array)

In [ ]:
new_array.resize(500,3)

In [ ]:
new_array

array([[411, 406, 392],
       [327, 291,   0],
       [410, 472, 410],
       [260, 268,   0],
       [304, 383,   0],
       [349, 338,   0],
       [391, 490,   0],
       [472, 292, 493],
       [430, 432, 488],
       [466, 251, 452],
       [338, 425, 261],
       [416, 427, 417],
       [412, 368,   0],
       [470, 469, 456],
       [263, 368,   0],
       [326, 460,   0],
       [482, 476, 196],
       [265, 263,   0],
       [278, 400, 424],
       [485, 331, 299],
       [346, 254,   0],
       [382, 281,   0],
       [316, 265,   0],
       [399, 355,   0],
       [457, 265,   0],
       [260, 409,   0],
       [468, 309, 410],
       [397, 411, 452],
       [298, 370, 414],
       [380, 399,   0],
       [288, 357,   0],
       [289, 287, 481],
       [429, 303, 311],
       [496, 264, 353],
       [272, 312,   0],
       [476, 289,   0],
       [273, 316,   0],
       [453, 472, 417],
       [464, 263,   0],
       [458, 490, 409],
       [290, 452,   0],
       [425, 432

In [ ]:
new_array[2,0]

410

In [ ]:
p=[]
for i in range(500):
  for j in range(0,3):
    if ans== X[i,j]:
      p.append(i+1)
      p.append(new_array[i,j])
p= np.array(p)
len_p= int((np.size(p))/2)
p.resize(len_p,2)

In [ ]:
import pandas as pd
df=pd.DataFrame(p)
df

0    1
0      2  291
1      3  472
2      4  268
3      5  304
4      7  391
..   ...  ...
314  491  287
315  495  260
316  496    0
317  498  499
318  499  494

[319 rows x 2 columns]

In [ ]:
df1=df.sort_values(1,ascending=False)
df1

0    1
317  498  499
103  168  498
277  434  498
230  373  497
299  469  497
..   ...  ...
8     15    0
112  185    0
110  181    0
109  179    0
279  439    0

[319 rows x 2 columns]

In [ ]:
df2=(df1.head(60))
df2=df2.set_index(0)
df2

1
0       
498  499
168  498
434  498
373  497
469  497
435  497
68   497
286  496
112  496
225  495
499  494
468  494
105  490
388  489
90   487
184  487
278  486
210  484
176  484
470  482
17   482
332  480
214  480
234  479
326  479
233  477
443  476
136  476
264  475
426  474
8    472
250  472
3    472
101  471
121  470
14   470
382  470
490  469
350  468
174  468
355  467
280  464
39   464
127  463
375  463
252  462
203  462
186  460
254  460
452  460
425  457
77   454
371  453
301  452
95   452
41   452
269  450
427  450
156  449
423  448

In [ ]:
df3=pd.DataFrame(sum)
df3=df3.set_index(0)
df3

1
0        
1    1209
2    1491
3    1292
4    1421
5    1322
..    ...
496  1167
497  1396
498  1075
499  1063
500  1029

[500 rows x 1 columns]

In [ ]:
number= np.array(df2[1])
len= np.size(number)

In [ ]:
id= np.array(df1[0])

In [ ]:
Array=[]
for i in range(len):
  Array.append(id[i]) 
  Array.append(number[i])
Array=np.array(Array)
Array.resize(len,2)
Array

array([[498, 499],
       [168, 498],
       [434, 498],
       [373, 497],
       [469, 497],
       [435, 497],
       [ 68, 497],
       [286, 496],
       [112, 496],
       [225, 495],
       [499, 494],
       [468, 494],
       [105, 490],
       [388, 489],
       [ 90, 487],
       [184, 487],
       [278, 486],
       [210, 484],
       [176, 484],
       [470, 482],
       [ 17, 482],
       [332, 480],
       [214, 480],
       [234, 479],
       [326, 479],
       [233, 477],
       [443, 476],
       [136, 476],
       [264, 475],
       [426, 474],
       [  8, 472],
       [250, 472],
       [  3, 472],
       [101, 471],
       [121, 470],
       [ 14, 470],
       [382, 470],
       [490, 469],
       [350, 468],
       [174, 468],
       [355, 467],
       [280, 464],
       [ 39, 464],
       [127, 463],
       [375, 463],
       [252, 462],
       [203, 462],
       [186, 460],
       [254, 460],
       [452, 460],
       [425, 457],
       [ 77, 454],
       [371,

In [ ]:
len=(np.size(Array))
len= int(len)
len=len/2
len=int(len)

In [ ]:
for i in range(500):
  for k in range(len):
      if sum[i][0]==Array[k][0]:
        sum[i][1]= sum[i][1]-Array[k][1]
      else:
        sum[i][1]= sum[i][1]
sum

array([[   1, 1209],
       [   2, 1491],
       [   3,  820],
       [   4, 1421],
       [   5, 1322],
       [   6, 1412],
       [   7, 1402],
       [   8,  785],
       [   9, 1350],
       [  10, 1169],
       [  11, 1024],
       [  12, 1260],
       [  13, 1381],
       [  14,  925],
       [  15, 1495],
       [  16, 1418],
       [  17,  672],
       [  18, 1345],
       [  19, 1102],
       [  20, 1115],
       [  21, 1294],
       [  22, 1203],
       [  23, 1309],
       [  24, 1483],
       [  25, 1244],
       [  26, 1234],
       [  27, 1187],
       [  28, 1260],
       [  29, 1082],
       [  30, 1336],
       [  31, 1440],
       [  32, 1057],
       [  33, 1043],
       [  34, 1113],
       [  35, 1402],
       [  36, 1384],
       [  37, 1409],
       [  38, 1342],
       [  39, 1008],
       [  40, 1357],
       [  41, 1022],
       [  42, 1441],
       [  43, 1299],
       [  44, 1122],
       [  45, 1200],
       [  46, 1462],
       [  47, 1400],
       [  48,

In [ ]:
a=[]
for i in range(500):
  a.append(sum[i][1])
a=np.array(a)
df_1['Total_money']=a

In [ ]:
x=[]
for i in range(500):
  x.append(i+1)
  x.append(0)
x=np.array(x)
x.resize(500,2)
for i in range(500):
  for j in range(len):
    if Array[j][0]==x[i][0]:
      x[i][1]=1
x

array([[  1,   0],
       [  2,   0],
       [  3,   1],
       [  4,   0],
       [  5,   0],
       [  6,   0],
       [  7,   0],
       [  8,   1],
       [  9,   0],
       [ 10,   0],
       [ 11,   0],
       [ 12,   0],
       [ 13,   0],
       [ 14,   1],
       [ 15,   0],
       [ 16,   0],
       [ 17,   1],
       [ 18,   0],
       [ 19,   0],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   0],
       [ 24,   0],
       [ 25,   0],
       [ 26,   0],
       [ 27,   0],
       [ 28,   0],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   0],
       [ 34,   0],
       [ 35,   0],
       [ 36,   0],
       [ 37,   0],
       [ 38,   0],
       [ 39,   1],
       [ 40,   0],
       [ 41,   1],
       [ 42,   0],
       [ 43,   0],
       [ 44,   0],
       [ 45,   0],
       [ 46,   0],
       [ 47,   0],
       [ 48,   0],
       [ 49,   0],
       [ 50,   0],
       [ 51,   0],
       [ 52,   0],
       [ 53,

In [ ]:
ll=[]
for i in range(500):
  ll.append(x[i][1])
ll=np.array(ll)
ll

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
df_1[ans]=ll

In [ ]:
df_1['SUM']=df_1['A']+df_1['B']+df_1['C']+df_1['D']+df_1['E']
df_1

Customer_ID  Total_money  A  B  C  D  E  SUM
0              1         1209  0  0  0  0  0    0
1              2         1491  0  0  0  0  0    0
2              3          820  0  0  1  0  0    1
3              4         1421  0  0  0  0  0    0
4              5         1322  0  0  0  0  0    0
..           ...          ... .. .. .. .. ..  ...
495          496         1167  0  0  0  0  0    0
496          497         1396  0  0  0  0  0    0
497          498          576  0  0  1  0  0    1
498          499          569  0  0  1  0  0    1
499          500         1029  0  0  0  0  0    0

[500 rows x 8 columns]

In [ ]:
stocks.remove(ans)
stocks

['A', 'B', 'D', 'E']

In [ ]:
z=['none']
a= np.array(df_1[ans])
X=[]
for i in range(500):
  if a[i]==1:
    x=random.sample(stocks,2)
    X=X+x
    X=X+z
  else:
    x=random.sample(stocks,3)
    X=X+x
X=np.array(X)
X.resize(500,3)
X

array([['E', 'D', 'B'],
       ['B', 'A', 'D'],
       ['D', 'A', 'none'],
       ['E', 'D', 'B'],
       ['E', 'A', 'D'],
       ['D', 'E', 'B'],
       ['D', 'E', 'A'],
       ['A', 'D', 'none'],
       ['B', 'D', 'A'],
       ['E', 'B', 'D'],
       ['E', 'D', 'A'],
       ['A', 'B', 'D'],
       ['D', 'E', 'B'],
       ['D', 'A', 'none'],
       ['E', 'A', 'D'],
       ['A', 'E', 'B'],
       ['A', 'E', 'none'],
       ['B', 'D', 'A'],
       ['A', 'B', 'D'],
       ['E', 'B', 'D'],
       ['E', 'A', 'B'],
       ['B', 'E', 'D'],
       ['E', 'B', 'A'],
       ['A', 'D', 'B'],
       ['B', 'D', 'A'],
       ['E', 'B', 'A'],
       ['B', 'A', 'E'],
       ['B', 'A', 'E'],
       ['D', 'A', 'E'],
       ['A', 'B', 'D'],
       ['B', 'D', 'E'],
       ['B', 'A', 'D'],
       ['B', 'D', 'E'],
       ['E', 'B', 'D'],
       ['D', 'A', 'E'],
       ['D', 'B', 'A'],
       ['A', 'D', 'E'],
       ['B', 'D', 'A'],
       ['B', 'E', 'none'],
       ['E', 'B', 'D'],
       ['D', 'B', 'none']

In [ ]:
a1= np.char.count(X,'A')
sum_a1= a1.sum()
b1= np.char.count(X,'B')
sum_b1= b1.sum()
c1= np.char.count(X,'C')
sum_c1= c1.sum()
d1= np.char.count(X,'D')
sum_d1=d1.sum()
e1= np.char.count(X,'E')
sum_e1=e1.sum()
sum1= [sum_a1,sum_b1,sum_c1,sum_d1,sum_e1]
sum1

[365, 366, 0, 365, 344]

In [ ]:
max1= max(sum1)
if max1 == sum_a1:
  print('A')
  ans='A'
elif max1 == sum_b1:
  print('B')
  ans='B'
elif max1 == sum_c1:
  print('C')
  ans='C'
elif max1 == sum_d1:
  print('D')
  ans='D'
elif max1 == sum_e1:
  print('E')
  ans='E'

B


In [ ]:
money= np.array(df_1['Total_money'])
new_array=[]
for i in range(500):
  for j in range(0,3):
    if a[i]==1:
      if j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]=money[i]-inv_share
      elif j==1:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
      elif j==2:
        new_array.append(0)
    else:
      if j==1 or j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]= money[i]-inv_share
      if j==2:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
new_array= np.array(new_array)
new_array.resize(500,3)
new_array

array([[397, 459, 353],
       [396, 350,   0],
       [390, 430,   0],
       [495, 475, 451],
       [253, 499,   0],
       [345, 275,   0],
       [314, 254,   0],
       [448, 337,   0],
       [436, 462, 452],
       [362, 397, 410],
       [441, 270, 313],
       [289, 399,   0],
       [283, 337,   0],
       [311,   0,   0],
       [379, 343,   0],
       [256, 468,   0],
       [446, 226,   0],
       [302, 308,   0],
       [293, 258,   0],
       [274, 366, 475],
       [286, 251,   0],
       [361, 444, 398],
       [436, 250,   0],
       [445, 293,   0],
       [461, 422, 361],
       [302, 251,   0],
       [408, 462, 317],
       [305, 410,   0],
       [432, 449, 201],
       [473, 296,   0],
       [358, 332,   0],
       [417, 352, 288],
       [480, 395, 168],
       [436, 456, 221],
       [424, 460,   0],
       [423, 342,   0],
       [423, 286,   0],
       [436, 477, 429],
       [326,   0,   0],
       [426, 356,   0],
       [399,   0,   0],
       [411, 263

In [ ]:
p=[]
for i in range(500):
  for j in range(0,3):
    if ans== X[i,j]:
      p.append(i+1)
      p.append(new_array[i,j])
p= np.array(p)
len_p= int((np.size(p))/2)
p.resize(len_p,2)

In [ ]:
df=pd.DataFrame(p)
df

0    1
0      1  353
1      2  396
2      4  451
3      6    0
4      9  436
..   ...  ...
361  494    0
362  496  469
363  497  450
364  499  195
365  500  432

[366 rows x 2 columns]

In [ ]:
df1=df.sort_values(1,ascending=False)
df1

0    1
176  245  499
233  321  498
272  371  498
247  337  497
308  417  493
..   ...  ...
110  145    0
112  147    0
113  149    0
46    60    0
175  244    0

[366 rows x 2 columns]

In [ ]:
df2=(df1.head(60))
df2=df2.set_index(0)
df2

1
0       
245  499
321  498
371  498
337  497
417  493
286  493
253  491
383  490
146  490
224  489
363  488
86   486
119  486
211  485
144  484
55   482
48   480
33   480
197  479
407  478
261  477
450  475
460  475
68   475
448  473
415  473
150  473
446  472
357  471
457  471
196  470
496  469
302  464
242  462
393  462
303  461
126  461
25   461
238  460
390  458
114  457
358  457
80   457
34   456
336  454
4    451
412  450
497  450
365  446
56   445
76   445
379  445
289  444
369  444
237  444
136  442
491  441
269  441
167  441
402  440

In [ ]:
df3=pd.DataFrame(sum)
df3=df3.set_index(0)
df3

1
0        
1    1209
2    1491
3     820
4    1421
5    1322
..    ...
496  1167
497  1396
498   576
499   569
500  1029

[500 rows x 1 columns]

In [ ]:
number= np.array(df2[1])
len= np.size(number)
id= np.array(df1[0])
Array=[]
for i in range(len):
  Array.append(id[i]) 
  Array.append(number[i])
Array=np.array(Array)
Array.resize(len,2)
Array

array([[245, 499],
       [321, 498],
       [371, 498],
       [337, 497],
       [417, 493],
       [286, 493],
       [253, 491],
       [383, 490],
       [146, 490],
       [224, 489],
       [363, 488],
       [ 86, 486],
       [119, 486],
       [211, 485],
       [144, 484],
       [ 55, 482],
       [ 48, 480],
       [ 33, 480],
       [197, 479],
       [407, 478],
       [261, 477],
       [450, 475],
       [460, 475],
       [ 68, 475],
       [448, 473],
       [415, 473],
       [150, 473],
       [446, 472],
       [357, 471],
       [457, 471],
       [196, 470],
       [496, 469],
       [302, 464],
       [242, 462],
       [393, 462],
       [303, 461],
       [126, 461],
       [ 25, 461],
       [238, 460],
       [390, 458],
       [114, 457],
       [358, 457],
       [ 80, 457],
       [ 34, 456],
       [336, 454],
       [  4, 451],
       [412, 450],
       [497, 450],
       [365, 446],
       [ 56, 445],
       [ 76, 445],
       [379, 445],
       [289,

In [ ]:
len=(np.size(Array))
len= int(len)
len=len/2
len=int(len)
for i in range(500):
  for k in range(len):
      if sum[i][0]==Array[k][0]:
        sum[i][1]= sum[i][1]-Array[k][1]
      else:
        sum[i][1]= sum[i][1]
sum

array([[   1, 1209],
       [   2, 1491],
       [   3,  820],
       [   4,  970],
       [   5, 1322],
       [   6, 1412],
       [   7, 1402],
       [   8,  785],
       [   9, 1350],
       [  10, 1169],
       [  11, 1024],
       [  12, 1260],
       [  13, 1381],
       [  14,  925],
       [  15, 1495],
       [  16, 1418],
       [  17,  672],
       [  18, 1345],
       [  19, 1102],
       [  20, 1115],
       [  21, 1294],
       [  22, 1203],
       [  23, 1309],
       [  24, 1483],
       [  25,  783],
       [  26, 1234],
       [  27, 1187],
       [  28, 1260],
       [  29, 1082],
       [  30, 1336],
       [  31, 1440],
       [  32, 1057],
       [  33,  563],
       [  34,  657],
       [  35, 1402],
       [  36, 1384],
       [  37, 1409],
       [  38, 1342],
       [  39, 1008],
       [  40, 1357],
       [  41, 1022],
       [  42, 1441],
       [  43, 1299],
       [  44, 1122],
       [  45, 1200],
       [  46, 1462],
       [  47, 1400],
       [  48,

In [ ]:
a=[]
for i in range(500):
  a.append(sum[i][1])
a=np.array(a)
df_1['Total_money']=a
x=[]
for i in range(500):
  x.append(i+1)
  x.append(0)
x=np.array(x)
x.resize(500,2)
for i in range(500):
  for j in range(len):
    if Array[j][0]==x[i][0]:
      x[i][1]=1
x

array([[  1,   0],
       [  2,   0],
       [  3,   0],
       [  4,   1],
       [  5,   0],
       [  6,   0],
       [  7,   0],
       [  8,   0],
       [  9,   0],
       [ 10,   0],
       [ 11,   0],
       [ 12,   0],
       [ 13,   0],
       [ 14,   0],
       [ 15,   0],
       [ 16,   0],
       [ 17,   0],
       [ 18,   0],
       [ 19,   0],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   0],
       [ 24,   0],
       [ 25,   1],
       [ 26,   0],
       [ 27,   0],
       [ 28,   0],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   1],
       [ 34,   1],
       [ 35,   0],
       [ 36,   0],
       [ 37,   0],
       [ 38,   0],
       [ 39,   0],
       [ 40,   0],
       [ 41,   0],
       [ 42,   0],
       [ 43,   0],
       [ 44,   0],
       [ 45,   0],
       [ 46,   0],
       [ 47,   0],
       [ 48,   1],
       [ 49,   0],
       [ 50,   0],
       [ 51,   0],
       [ 52,   0],
       [ 53,

In [ ]:
ll=[]
for i in range(500):
  ll.append(x[i][1])
ll=np.array(ll)
ll

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
df_1[ans]=ll
df_1['SUM']=df_1['A']+df_1['B']+df_1['C']+df_1['D']+df_1['E']
df_1

Customer_ID  Total_money  A  B  C  D  E  SUM
0              1          823  0  0  0  0  1    1
1              2         1106  0  0  0  0  0    0
2              3         1082  0  0  0  0  0    0
3              4         1473  0  0  0  0  0    0
4              5         1328  0  0  0  0  0    0
..           ...          ... .. .. .. .. ..  ...
495          496         1234  0  0  0  0  0    0
496          497         1407  0  0  0  0  0    0
497          498         1432  0  0  0  0  0    0
498          499         1415  0  0  0  0  0    0
499          500          661  1  0  0  0  0    1

[500 rows x 8 columns]

In [ ]:
stocks.remove(ans)
stocks

['B', 'C', 'D']

In [ ]:
z=['none']
a= np.array(df_1['SUM'])
X=[]
for i in range(500):
  if a[i]==2:
    x=random.sample(stocks,1)
    X=X+x
    X=X+z
    X=X+z
  if a[i]==1:
    x=random.sample(stocks,2)
    X=X+x
    X=X+z
  if a[i]==0:
    x=random.sample(stocks,3)
    X=X+x
X=np.array(X)
X.resize(500,3)
X

array([['D', 'B', 'none'],
       ['C', 'B', 'D'],
       ['D', 'B', 'C'],
       ['B', 'C', 'D'],
       ['C', 'D', 'B'],
       ['C', 'D', 'B'],
       ['B', 'D', 'C'],
       ['C', 'B', 'D'],
       ['B', 'D', 'C'],
       ['C', 'B', 'D'],
       ['D', 'B', 'C'],
       ['D', 'C', 'B'],
       ['D', 'B', 'none'],
       ['C', 'B', 'D'],
       ['D', 'B', 'C'],
       ['C', 'D', 'B'],
       ['C', 'B', 'none'],
       ['B', 'C', 'D'],
       ['D', 'C', 'B'],
       ['B', 'C', 'none'],
       ['D', 'C', 'none'],
       ['D', 'none', 'none'],
       ['D', 'B', 'none'],
       ['C', 'B', 'D'],
       ['C', 'B', 'D'],
       ['D', 'B', 'C'],
       ['B', 'C', 'D'],
       ['B', 'D', 'C'],
       ['C', 'D', 'B'],
       ['B', 'D', 'C'],
       ['D', 'B', 'C'],
       ['B', 'C', 'none'],
       ['C', 'B', 'none'],
       ['C', 'B', 'none'],
       ['D', 'C', 'B'],
       ['D', 'C', 'B'],
       ['D', 'C', 'B'],
       ['C', 'B', 'D'],
       ['D', 'C', 'B'],
       ['C', 'B', 'D'],
       

In [ ]:
a1= np.char.count(X,'A')
sum_a1= a1.sum()
b1= np.char.count(X,'B')
sum_b1= b1.sum()
c1= np.char.count(X,'C')
sum_c1= c1.sum()
d1= np.char.count(X,'D')
sum_d1=d1.sum()
e1= np.char.count(X,'E')
sum_e1=e1.sum()
sum1= [sum_a1,sum_b1,sum_c1,sum_d1,sum_e1]
sum1

[0, 467, 459, 454, 0]

In [ ]:
max1= max(sum1)
if max1 == sum_a1:
  print('A')
  ans='A'
elif max1 == sum_b1:
  print('B')
  ans='B'
elif max1 == sum_c1:
  print('C')
  ans='C'
elif max1 == sum_d1:
  print('D')
  ans='D'
elif max1 == sum_e1:
  print('E')
  ans='E'

B


In [ ]:
money= np.array(df_1['Total_money'])
a= np.array(df_1['SUM'])
new_array=[]
for i in range(500):
  for j in range(0,3):
    if a[i]==2:
      if j==0:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
      elif j==1: 
        new_array.append(0)
      elif j==2:
        new_array.append(0)
    elif a[i]==1:
      if j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]=money[i]-inv_share
      elif j==1:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
      elif j==2:
        new_array.append(0)
    elif a[i]==0:
      if j==1 or j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]= money[i]-inv_share
      if j==2:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
new_array= np.array(new_array)
new_array.resize(500,3)
new_array

array([[396, 427,   0],
       [448, 496, 162],
       [390, 440, 252],
       [496, 468,   0],
       [460, 356,   0],
       [427, 424, 476],
       [334, 420, 284],
       [265, 394,   0],
       [353, 484,   0],
       [409, 472, 354],
       [385, 490,   0],
       [313, 272, 443],
       [466, 313,   0],
       [398, 283,   0],
       [335, 396,   0],
       [274, 402, 496],
       [282,   0,   0],
       [402, 353, 348],
       [453, 484, 391],
       [316, 335,   0],
       [355, 448,   0],
       [101,   0,   0],
       [289, 489,   0],
       [395, 423, 469],
       [335, 262,   0],
       [340, 258,   0],
       [497, 419, 433],
       [472, 436, 206],
       [373, 318,   0],
       [403, 354,   0],
       [372, 425, 440],
       [396, 243,   0],
       [372, 373,   0],
       [437, 416,   0],
       [480, 456, 431],
       [325, 498,   0],
       [430, 439,   0],
       [452, 331,   0],
       [357, 418, 250],
       [301, 356, 446],
       [350, 324, 360],
       [398, 482

In [ ]:
p=[]
for i in range(500):
  for j in range(0,3):
    if ans== X[i,j]:
      p.append(i+1)
      p.append(new_array[i,j])
p= np.array(p)
len_p= int((np.size(p))/2)
p.resize(len_p,2)

In [ ]:
df=pd.DataFrame(p)
df

0    1
0      1  427
1      2  496
2      3  440
3      4  496
4      5    0
..   ...  ...
462  495  379
463  496  387
464  497  374
465  498    0
466  499    0

[467 rows x 2 columns]

In [ ]:
df1=df.sort_values(1,ascending=False)
df1

0    1
111  117  499
286  304  499
228  241  498
56    59  497
24    27  497
..   ...  ...
296  314    0
57    60    0
285  303    0
271  289    0
466  499    0

[467 rows x 2 columns]

In [ ]:
df2=(df1.head(60))
df2=df2.set_index(0)
df2

1
0       
117  499
304  499
241  498
59   497
27   497
165  497
294  497
85   497
2    496
16   496
4    496
453  495
448  495
312  495
409  494
166  493
159  492
455  492
476  492
179  491
11   490
384  489
23   489
490  488
129  488
65   487
262  487
83   487
242  486
81   486
118  483
400  482
307  481
320  479
168  479
306  478
376  478
366  476
6    476
377  475
261  475
479  474
185  474
10   472
482  472
28   472
298  471
309  470
484  469
315  469
264  469
310  466
343  466
246  466
358  465
147  465
462  463
138  462
458  462
370  462

In [ ]:
df3=pd.DataFrame(sum)
df3=df3.set_index(0)
df3

1
0        
1     823
2    1106
3    1082
4    1473
5    1328
..    ...
496  1234
497  1407
498  1432
499  1415
500   661

[500 rows x 1 columns]

In [ ]:
number= np.array(df2[1])
len= np.size(number)
id= np.array(df1[0])
Array=[]
for i in range(len):
  Array.append(id[i]) 
  Array.append(number[i])
Array=np.array(Array)
Array.resize(len,2)
Array

array([[117, 499],
       [304, 499],
       [241, 498],
       [ 59, 497],
       [ 27, 497],
       [165, 497],
       [294, 497],
       [ 85, 497],
       [  2, 496],
       [ 16, 496],
       [  4, 496],
       [453, 495],
       [448, 495],
       [312, 495],
       [409, 494],
       [166, 493],
       [159, 492],
       [455, 492],
       [476, 492],
       [179, 491],
       [ 11, 490],
       [384, 489],
       [ 23, 489],
       [490, 488],
       [129, 488],
       [ 65, 487],
       [262, 487],
       [ 83, 487],
       [242, 486],
       [ 81, 486],
       [118, 483],
       [400, 482],
       [307, 481],
       [320, 479],
       [168, 479],
       [306, 478],
       [376, 478],
       [366, 476],
       [  6, 476],
       [377, 475],
       [261, 475],
       [479, 474],
       [185, 474],
       [ 10, 472],
       [482, 472],
       [ 28, 472],
       [298, 471],
       [309, 470],
       [484, 469],
       [315, 469],
       [264, 469],
       [310, 466],
       [343,

In [ ]:
len=(np.size(Array))
len= int(len)
len=len/2
len=int(len)
for i in range(500):
  for k in range(len):
      if sum[i][0]==Array[k][0]:
        sum[i][1]= sum[i][1]-Array[k][1]
      else:
        sum[i][1]= sum[i][1]
sum

array([[   1,  823],
       [   2,  610],
       [   3, 1082],
       [   4,  977],
       [   5, 1328],
       [   6,  851],
       [   7, 1038],
       [   8, 1479],
       [   9, 1418],
       [  10,  763],
       [  11,  944],
       [  12, 1028],
       [  13,  779],
       [  14, 1453],
       [  15, 1283],
       [  16,  676],
       [  17,  842],
       [  18, 1103],
       [  19, 1328],
       [  20,  651],
       [  21,  803],
       [  22,  101],
       [  23,  289],
       [  24, 1287],
       [  25, 1119],
       [  26, 1210],
       [  27,  852],
       [  28,  642],
       [  29, 1376],
       [  30, 1304],
       [  31, 1237],
       [  32,  639],
       [  33,  745],
       [  34,  853],
       [  35, 1367],
       [  36, 1364],
       [  37, 1451],
       [  38, 1307],
       [  39, 1025],
       [  40, 1103],
       [  41, 1034],
       [  42, 1193],
       [  43,  636],
       [  44, 1191],
       [  45, 1311],
       [  46, 1448],
       [  47, 1149],
       [  48,

In [ ]:
a=[]
for i in range(500):
  a.append(sum[i][1])
a=np.array(a)
df_1['Total_money']=a
x=[]
for i in range(500):
  x.append(i+1)
  x.append(0)
x=np.array(x)
x.resize(500,2)
for i in range(500):
  for j in range(len):
    if Array[j][0]==x[i][0]:
      x[i][1]=1
x

array([[  1,   0],
       [  2,   1],
       [  3,   0],
       [  4,   1],
       [  5,   0],
       [  6,   1],
       [  7,   0],
       [  8,   0],
       [  9,   0],
       [ 10,   1],
       [ 11,   1],
       [ 12,   0],
       [ 13,   0],
       [ 14,   0],
       [ 15,   0],
       [ 16,   1],
       [ 17,   0],
       [ 18,   0],
       [ 19,   0],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   1],
       [ 24,   0],
       [ 25,   0],
       [ 26,   0],
       [ 27,   1],
       [ 28,   1],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   0],
       [ 34,   0],
       [ 35,   0],
       [ 36,   0],
       [ 37,   0],
       [ 38,   0],
       [ 39,   0],
       [ 40,   0],
       [ 41,   0],
       [ 42,   0],
       [ 43,   0],
       [ 44,   0],
       [ 45,   0],
       [ 46,   0],
       [ 47,   0],
       [ 48,   0],
       [ 49,   0],
       [ 50,   0],
       [ 51,   0],
       [ 52,   0],
       [ 53,

In [ ]:
ll=[]
for i in range(500):
  ll.append(x[i][1])
ll=np.array(ll)
ll

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,

In [ ]:
df_1[ans]=ll
df_1['SUM']=df_1['A']+df_1['B']+df_1['C']+df_1['D']+df_1['E']
df_1

Customer_ID  Total_money  A  B  C  D  E  SUM
0              1          823  0  0  0  0  1    1
1              2          610  0  1  0  0  0    1
2              3         1082  0  0  0  0  0    0
3              4          977  0  1  0  0  0    1
4              5         1328  0  0  0  0  0    0
..           ...          ... .. .. .. .. ..  ...
495          496         1234  0  0  0  0  0    0
496          497         1407  0  0  0  0  0    0
497          498         1432  0  0  0  0  0    0
498          499         1415  0  0  0  0  0    0
499          500          661  1  0  0  0  0    1

[500 rows x 8 columns]

In [ ]:
stocks.remove(ans)
stocks

['C', 'D']

In [ ]:
z=['none']
a= np.array(df_1['SUM'])
X=[]
for i in range(500):
  if a[i]==2:
    x=random.sample(stocks,1)
    X=X+x
    X=X+z
    X=X+z
  if a[i]==1:
    x=random.sample(stocks,2)
    X=X+x
    X=X+z
  if a[i]==0:
    x=random.sample(stocks,2)
    X=X+x
    X=X+z
X=np.array(X)
X.resize(500,3)
X

array([['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'none'],
       ['D', 'C', 'none'],
       ['C', 'D', 'none'],
       ['C', 'D', 'none'],
       ['D', 'C', 'non

In [ ]:
a1= np.char.count(X,'A')
sum_a1= a1.sum()
b1= np.char.count(X,'B')
sum_b1= b1.sum()
c1= np.char.count(X,'C')
sum_c1= c1.sum()
d1= np.char.count(X,'D')
sum_d1=d1.sum()
e1= np.char.count(X,'E')
sum_e1=e1.sum()
sum1= [sum_a1,sum_b1,sum_c1,sum_d1,sum_e1]
sum1

[0, 0, 492, 494, 0]

In [ ]:
max1= max(sum1)
if max1 == sum_a1:
  print('A')
  ans='A'
elif max1 == sum_b1:
  print('B')
  ans='B'
elif max1 == sum_c1:
  print('C')
  ans='C'
elif max1 == sum_d1:
  print('D')
  ans='D'
elif max1 == sum_e1:
  print('E')
  ans='E'

D


In [ ]:
money= np.array(df_1['Total_money'])
a= np.array(df_1['SUM'])
new_array=[]
for i in range(500):
  for j in range(0,3):
    if a[i]==3:
      if j==0:
        new_array.append(0)
      elif j==1:
        new_array.append(0)
      elif j==2:
        new_array.append(0)
    if a[i]==2:
      if j==0:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
      elif j==1: 
        new_array.append(0)
      elif j==2:
        new_array.append(0)
    elif a[i]==1:
      if j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]=money[i]-inv_share
      elif j==1:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
      elif j==2:
        new_array.append(0)
    elif a[i]==0:
      if j==1 or j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]= money[i]-inv_share
      if j==2:
        inv_share= money[i]
        if 250<inv_share<500:
          new_array.append(inv_share)
        else:
          new_array.append(0)
new_array= np.array(new_array)
new_array.resize(500,3)
new_array

array([[449, 374,   0],
       [491, 119,   0],
       [382, 291, 409],
       [460,   0,   0],
       [310, 428,   0],
       [366, 485,   0],
       [392, 298, 348],
       [320, 464,   0],
       [303, 495,   0],
       [463, 300,   0],
       [473, 471,   0],
       [283, 265, 480],
       [437, 342,   0],
       [374, 418,   0],
       [293, 491, 499],
       [270, 406,   0],
       [259,   0,   0],
       [361, 402, 340],
       [449, 298,   0],
       [438, 213,   0],
       [306, 497,   0],
       [101,   0,   0],
       [289,   0,   0],
       [487, 382, 418],
       [382, 488,   0],
       [308, 366,   0],
       [463, 389,   0],
       [405, 237,   0],
       [448, 310,   0],
       [422, 407, 475],
       [274, 307,   0],
       [270, 369,   0],
       [432, 313,   0],
       [416, 437,   0],
       [498, 496, 373],
       [283, 411,   0],
       [369, 447,   0],
       [469, 499, 339],
       [487, 457,   0],
       [328, 257,   0],
       [272, 262,   0],
       [482, 441

In [ ]:
p=[]
for i in range(500):
  for j in range(0,3):
    if ans== X[i,j]:
      p.append(i+1)
      p.append(new_array[i,j])
p= np.array(p)
len_p= int((np.size(p))/2)
p.resize(len_p,2)

In [ ]:
df=pd.DataFrame(p)
df

0    1
0      1  374
1      2  491
2      3  382
3      4  460
4      5  310
..   ...  ...
489  496  400
490  497  346
491  498  483
492  499  422
493  500  388

[494 rows x 2 columns]

In [ ]:
df1=df.sort_values(1,ascending=False)
df1

0    1
377  381  499
35    38  499
419  423  498
458  464  498
170  173  498
..   ...  ...
85    88    0
141  144    0
452  458    0
450  456    0
303  307    0

[494 rows x 2 columns]

In [ ]:
df2=(df1.head(60))
df2=df2.set_index(0)
df2

1
0       
381  499
38   499
423  498
464  498
173  498
417  497
149  497
35   496
231  496
61   495
219  495
9    495
378  494
124  493
127  492
2    491
77   491
137  490
475  490
270  490
264  489
39   487
55   487
420  485
6    485
279  485
308  484
120  483
128  483
66   483
498  483
58   482
309  482
297  481
241  481
274  478
242  478
446  478
447  477
60   475
494  474
366  474
182  473
53   473
485  473
374  471
208  471
162  471
11   471
240  471
486  471
196  470
87   469
151  469
245  468
224  468
473  468
449  467
168  467
112  467

In [ ]:
df3=pd.DataFrame(sum)
df3=df3.set_index(0)
df3

1
0        
1     823
2     610
3    1082
4     977
5    1328
..    ...
496  1234
497  1407
498  1432
499  1415
500   661

[500 rows x 1 columns]

In [ ]:
number= np.array(df2[1])
len= np.size(number)
id= np.array(df1[0])
Array=[]
for i in range(len):
  Array.append(id[i]) 
  Array.append(number[i])
Array=np.array(Array)
Array.resize(len,2)
Array

array([[381, 499],
       [ 38, 499],
       [423, 498],
       [464, 498],
       [173, 498],
       [417, 497],
       [149, 497],
       [ 35, 496],
       [231, 496],
       [ 61, 495],
       [219, 495],
       [  9, 495],
       [378, 494],
       [124, 493],
       [127, 492],
       [  2, 491],
       [ 77, 491],
       [137, 490],
       [475, 490],
       [270, 490],
       [264, 489],
       [ 39, 487],
       [ 55, 487],
       [420, 485],
       [  6, 485],
       [279, 485],
       [308, 484],
       [120, 483],
       [128, 483],
       [ 66, 483],
       [498, 483],
       [ 58, 482],
       [309, 482],
       [297, 481],
       [241, 481],
       [274, 478],
       [242, 478],
       [446, 478],
       [447, 477],
       [ 60, 475],
       [494, 474],
       [366, 474],
       [182, 473],
       [ 53, 473],
       [485, 473],
       [374, 471],
       [208, 471],
       [162, 471],
       [ 11, 471],
       [240, 471],
       [486, 471],
       [196, 470],
       [ 87,

In [ ]:
len=(np.size(Array))
len= int(len)
len=len/2
len=int(len)
for i in range(500):
  for k in range(len):
      if sum[i][0]==Array[k][0]:
        sum[i][1]= sum[i][1]-Array[k][1]
      else:
        sum[i][1]= sum[i][1]
sum

array([[   1,  823],
       [   2,  119],
       [   3, 1082],
       [   4,  977],
       [   5, 1328],
       [   6,  366],
       [   7, 1038],
       [   8, 1479],
       [   9,  923],
       [  10,  763],
       [  11,  473],
       [  12, 1028],
       [  13,  779],
       [  14, 1453],
       [  15, 1283],
       [  16,  676],
       [  17,  842],
       [  18, 1103],
       [  19, 1328],
       [  20,  651],
       [  21,  803],
       [  22,  101],
       [  23,  289],
       [  24, 1287],
       [  25, 1119],
       [  26, 1210],
       [  27,  852],
       [  28,  642],
       [  29, 1376],
       [  30, 1304],
       [  31, 1237],
       [  32,  639],
       [  33,  745],
       [  34,  853],
       [  35,  871],
       [  36, 1364],
       [  37, 1451],
       [  38,  808],
       [  39,  538],
       [  40, 1103],
       [  41, 1034],
       [  42, 1193],
       [  43,  636],
       [  44, 1191],
       [  45, 1311],
       [  46, 1448],
       [  47, 1149],
       [  48,

In [ ]:
a=[]
for i in range(500):
  a.append(sum[i][1])
a=np.array(a)
df_1['Total_money']=a
x=[]
for i in range(500):
  x.append(i+1)
  x.append(0)
x=np.array(x)
x.resize(500,2)
for i in range(500):
  for j in range(len):
    if Array[j][0]==x[i][0]:
      x[i][1]=1
x

array([[  1,   0],
       [  2,   1],
       [  3,   0],
       [  4,   0],
       [  5,   0],
       [  6,   1],
       [  7,   0],
       [  8,   0],
       [  9,   1],
       [ 10,   0],
       [ 11,   1],
       [ 12,   0],
       [ 13,   0],
       [ 14,   0],
       [ 15,   0],
       [ 16,   0],
       [ 17,   0],
       [ 18,   0],
       [ 19,   0],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   0],
       [ 24,   0],
       [ 25,   0],
       [ 26,   0],
       [ 27,   0],
       [ 28,   0],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   0],
       [ 34,   0],
       [ 35,   1],
       [ 36,   0],
       [ 37,   0],
       [ 38,   1],
       [ 39,   1],
       [ 40,   0],
       [ 41,   0],
       [ 42,   0],
       [ 43,   0],
       [ 44,   0],
       [ 45,   0],
       [ 46,   0],
       [ 47,   0],
       [ 48,   0],
       [ 49,   0],
       [ 50,   0],
       [ 51,   0],
       [ 52,   0],
       [ 53,

In [ ]:
ll=[]
for i in range(500):
  ll.append(x[i][1])
ll=np.array(ll)
ll

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
df_1[ans]=ll
df_1['SUM']=df_1['A']+df_1['B']+df_1['C']+df_1['D']+df_1['E']
df_1

Customer_ID  Total_money  A  B  C  D  E  SUM
0              1          823  0  0  0  0  1    1
1              2          119  0  1  0  1  0    2
2              3         1082  0  0  0  0  0    0
3              4          977  0  1  0  0  0    1
4              5         1328  0  0  0  0  0    0
..           ...          ... .. .. .. .. ..  ...
495          496         1234  0  0  0  0  0    0
496          497         1407  0  0  0  0  0    0
497          498          949  0  0  0  1  0    1
498          499         1415  0  0  0  0  0    0
499          500          661  1  0  0  0  0    1

[500 rows x 8 columns]

In [ ]:
stocks.remove(ans)
stocks

['C']

In [ ]:
z=['none']
a= np.array(df_1['SUM'])
X=[]
for i in range(500):
  if a[i]==2:
    x=random.sample(stocks,1)
    X=X+x
    X=X+z
    X=X+z
  if a[i]==1:
    x=random.sample(stocks,1)
    X=X+x
    X=X+z
    X=X+z
  if a[i]==0:
    x=random.sample(stocks,1)
    X=X+x
    X=X+z
    X=X+z
X=np.array(X)
X.resize(500,3)
X

array([['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C', 'none', 'none'],
       ['C

In [ ]:
a1= np.char.count(X,'A')
sum_a1= a1.sum()
b1= np.char.count(X,'B')
sum_b1= b1.sum()
c1= np.char.count(X,'C')
sum_c1= c1.sum()
d1= np.char.count(X,'D')
sum_d1=d1.sum()
e1= np.char.count(X,'E')
sum_e1=e1.sum()
sum1= [sum_a1,sum_b1,sum_c1,sum_d1,sum_e1]
sum1

[0, 0, 499, 0, 0]

In [ ]:
max1= max(sum1)
if max1 == sum_a1:
  print('A')
  ans='A'
elif max1 == sum_b1:
  print('B')
  ans='B'
elif max1 == sum_c1:
  print('C')
  ans='C'
elif max1 == sum_d1:
  print('D')
  ans='D'
elif max1 == sum_e1:
  print('E')
  ans='E'

C


In [ ]:
money= np.array(df_1['Total_money'])
a= np.array(df_1['SUM'])
new_array=[]
for i in range(500):
  for j in range(0,3):
    if a[i]==3:
      if j==0:
        new_array.append(0)
      elif j==1:
        new_array.append(0)
      elif j==2:
        new_array.append(0)
    if a[i]==2:
      if j==0:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
      elif j==1: 
        new_array.append(0)
      elif j==2:
        new_array.append(0)
    elif a[i]==1:
      if j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]=money[i]-inv_share
      elif j==1:
        inv_share= money[i]
        if inv_share>500:
          new_array.append(0)
        else:
          new_array.append(inv_share)
      elif j==2:
        new_array.append(0)
    elif a[i]==0:
      if j==1 or j==0:
        inv_share= np.random.choice(arr)
        new_array.append(inv_share)
        money[i]= money[i]-inv_share
      if j==2:
        inv_share= money[i]
        if 250<inv_share<500:
          new_array.append(inv_share)
        else:
          new_array.append(0)
new_array= np.array(new_array)
new_array.resize(500,3)
new_array

array([[459, 364,   0],
       [119,   0,   0],
       [433, 478,   0],
       [498, 479,   0],
       [464, 363,   0],
       [366,   0,   0],
       [452, 312, 274],
       [383, 256,   0],
       [426, 497,   0],
       [426, 337,   0],
       [473,   0,   0],
       [306, 431, 291],
       [474, 305,   0],
       [277, 403,   0],
       [391, 427, 465],
       [284, 392,   0],
       [317,   0,   0],
       [319, 460, 324],
       [494, 352, 482],
       [254, 397,   0],
       [347, 456,   0],
       [101,   0,   0],
       [289,   0,   0],
       [420, 421, 446],
       [386, 464, 269],
       [414, 390, 406],
       [283,   0,   0],
       [475, 167,   0],
       [348, 387,   0],
       [348, 296,   0],
       [402, 319,   0],
       [285, 354,   0],
       [297, 448,   0],
       [368, 485,   0],
       [426, 445,   0],
       [304, 446,   0],
       [476, 429,   0],
       [496, 312,   0],
       [386, 152,   0],
       [407, 328, 368],
       [279, 429, 326],
       [331, 362

In [ ]:
p=[]
for i in range(500):
  for j in range(0,3):
    if ans== X[i,j]:
      p.append(i+1)
      p.append(new_array[i,j])
p= np.array(p)
len_p= int((np.size(p))/2)
p.resize(len_p,2)

In [ ]:
df=pd.DataFrame(p)
df

0    1
0      1  459
1      2  119
2      3  433
3      4  498
4      5  464
..   ...  ...
494  495  459
495  496  316
496  497  322
497  498  322
498  499  456

[499 rows x 2 columns]

In [ ]:
df1=df.sort_values(1,ascending=False)
df1

0    1
194  195  499
249  250  498
142  143  498
3      4  498
191  192  498
..   ...  ...
230  231   94
207  208   89
422  423   52
457  458    0
240  241    0

[499 rows x 2 columns]

In [ ]:
df2=(df1.head(60))
df2=df2.set_index(0)
df2

1
0       
195  499
250  498
143  498
4    498
192  498
445  497
38   496
374  496
296  495
270  495
312  494
19   494
230  494
226  493
131  492
113  492
389  492
354  491
444  491
76   491
220  491
125  491
384  490
275  488
490  488
203  487
219  487
117  487
352  486
217  486
271  485
115  485
280  485
278  482
434  481
213  480
476  478
427  477
339  477
57   476
212  476
37   476
261  475
28   475
158  475
174  475
13   474
334  474
140  474
453  473
11   473
472  472
447  472
179  472
266  471
55   470
436  469
186  466
148  466
152  465

In [ ]:
df3=pd.DataFrame(sum)
df3=df3.set_index(0)
df3

1
0        
1     823
2     119
3    1082
4     977
5    1328
..    ...
496  1234
497  1407
498   949
499  1415
500   661

[500 rows x 1 columns]

In [ ]:
number= np.array(df2[1])
len= np.size(number)
id= np.array(df1[0])
Array=[]
for i in range(len):
  Array.append(id[i]) 
  Array.append(number[i])
Array=np.array(Array)
Array.resize(len,2)
Array

array([[195, 499],
       [250, 498],
       [143, 498],
       [  4, 498],
       [192, 498],
       [445, 497],
       [ 38, 496],
       [374, 496],
       [296, 495],
       [270, 495],
       [312, 494],
       [ 19, 494],
       [230, 494],
       [226, 493],
       [131, 492],
       [113, 492],
       [389, 492],
       [354, 491],
       [444, 491],
       [ 76, 491],
       [220, 491],
       [125, 491],
       [384, 490],
       [275, 488],
       [490, 488],
       [203, 487],
       [219, 487],
       [117, 487],
       [352, 486],
       [217, 486],
       [271, 485],
       [115, 485],
       [280, 485],
       [278, 482],
       [434, 481],
       [213, 480],
       [476, 478],
       [427, 477],
       [339, 477],
       [ 57, 476],
       [212, 476],
       [ 37, 476],
       [261, 475],
       [ 28, 475],
       [158, 475],
       [174, 475],
       [ 13, 474],
       [334, 474],
       [140, 474],
       [453, 473],
       [ 11, 473],
       [472, 472],
       [447,

In [ ]:
len=(np.size(Array))
len= int(len)
len=len/2
len=int(len)
for i in range(500):
  for k in range(len):
      if sum[i][0]==Array[k][0]:
        sum[i][1]= sum[i][1]-Array[k][1]
      else:
        sum[i][1]= sum[i][1]
sum

array([[   1,  823],
       [   2,  119],
       [   3, 1082],
       [   4,  479],
       [   5, 1328],
       [   6,  366],
       [   7, 1038],
       [   8, 1479],
       [   9,  923],
       [  10,  763],
       [  11,    0],
       [  12, 1028],
       [  13,  305],
       [  14, 1453],
       [  15, 1283],
       [  16,  676],
       [  17,  842],
       [  18, 1103],
       [  19,  834],
       [  20,  651],
       [  21,  803],
       [  22,  101],
       [  23,  289],
       [  24, 1287],
       [  25, 1119],
       [  26, 1210],
       [  27,  852],
       [  28,  167],
       [  29, 1376],
       [  30, 1304],
       [  31, 1237],
       [  32,  639],
       [  33,  745],
       [  34,  853],
       [  35,  871],
       [  36, 1364],
       [  37,  975],
       [  38,  312],
       [  39,  538],
       [  40, 1103],
       [  41, 1034],
       [  42, 1193],
       [  43,  636],
       [  44, 1191],
       [  45, 1311],
       [  46, 1448],
       [  47, 1149],
       [  48,

In [ ]:
a=[]
for i in range(500):
  a.append(sum[i][1])
a=np.array(a)
df_1['Total_money']=a
x=[]
for i in range(500):
  x.append(i+1)
  x.append(0)
x=np.array(x)
x.resize(500,2)
for i in range(500):
  for j in range(len):
    if Array[j][0]==x[i][0]:
      x[i][1]=1
x

array([[  1,   0],
       [  2,   0],
       [  3,   0],
       [  4,   1],
       [  5,   0],
       [  6,   0],
       [  7,   0],
       [  8,   0],
       [  9,   0],
       [ 10,   0],
       [ 11,   1],
       [ 12,   0],
       [ 13,   1],
       [ 14,   0],
       [ 15,   0],
       [ 16,   0],
       [ 17,   0],
       [ 18,   0],
       [ 19,   1],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   0],
       [ 24,   0],
       [ 25,   0],
       [ 26,   0],
       [ 27,   0],
       [ 28,   1],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   0],
       [ 34,   0],
       [ 35,   0],
       [ 36,   0],
       [ 37,   1],
       [ 38,   1],
       [ 39,   0],
       [ 40,   0],
       [ 41,   0],
       [ 42,   0],
       [ 43,   0],
       [ 44,   0],
       [ 45,   0],
       [ 46,   0],
       [ 47,   0],
       [ 48,   0],
       [ 49,   0],
       [ 50,   0],
       [ 51,   0],
       [ 52,   0],
       [ 53,

In [ ]:
ll=[]
for i in range(500):
  ll.append(x[i][1])
ll=np.array(ll)
ll

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [ ]:
df_1[ans]=ll
df_1['SUM']=df_1['A']+df_1['B']+df_1['C']+df_1['D']+df_1['E']
df_1

Customer_ID  Total_money  A  B  C  D  E  SUM
0              1          823  0  0  0  0  1    1
1              2          119  0  1  0  1  0    2
2              3         1082  0  0  0  0  0    0
3              4          479  0  1  1  0  0    2
4              5         1328  0  0  0  0  0    0
..           ...          ... .. .. .. .. ..  ...
495          496         1234  0  0  0  0  0    0
496          497         1407  0  0  0  0  0    0
497          498          949  0  0  0  1  0    1
498          499         1415  0  0  0  0  0    0
499          500          661  1  0  0  0  0    1

[500 rows x 8 columns]

In [ ]:
s= np.array(df_1['SUM'])
s.sum()

300